[package]
name = "Denux-Dashboard"
version = "0.1.0-alpha.1"
license = "AGPL-3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
yew-router = "0.16"
stylist = "0.10.1"