version: "3.8"
services:
  rust:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src/:/usr/src/dashboard/src
      - ./target/:/usr/src/dashboard/target
      - ./style:/usr/src/dashboard/style
      - ./assets:/usr/src/dashboard/assets
      - ./Cargo.toml:/usr/src/dashboard/Cargo.toml
      - ./Cargo.lock:/usr/src/dashboard/Cargo.lock
    ports:
      - "5739:8080"
