services:
  rust:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
    restart: unless-stopped
    environment:
      LEPTOS_SITE_ADDR: "0.0.0.0:8080"
    volumes:
      - ./src/:/usr/src/dashboard/src
      - ./style:/usr/src/dashboard/style
      - ./assets:/usr/src/dashboard/assets
      - ./Cargo.toml:/usr/src/dashboard/Cargo.toml
      - ./Cargo.lock:/usr/src/dashboard/Cargo.lock
    ports:
      - "127.0.0.1:5739:8080"
