name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup cargo leptos
      run: cargo install --locked cargo-leptos
    - name: Build
      run: cargo leptos build
    - name: Run tests
      run: cargo leptos test
