name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup wasm-pack
      run: cargo install wasm-pack
    - name: Building client-side
      run: wasm-pack build --target=web --debug --no-default-features --features=hydrate
    - name: Building server-side
      run: cargo build --no-default-features --features=ssr
    - name: Run tests
      run: cargo leptos test
